"""deleted google cred

Revision ID: f903d95d16c9
Revises: 38586d82a310
Create Date: 2024-10-01 12:00:01.676859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f903d95d16c9'
down_revision: Union[str, None] = '38586d82a310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credentials_google')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials_google',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('google_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='credentials_google_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='credentials_google_pkey'),
    sa.UniqueConstraint('google_user_id', name='credentials_google_google_user_id_key')
    )
    # ### end Alembic commands ###
